# Generated by Django 4.2.6 on 2023-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_course_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='license_term',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
