# Generated by Django 4.2.6 on 2023-10-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_license_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
