# Generated by Django 4.2.6 on 2023-11-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_api',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
